### ISSUE TITLE
Support label transformers as ballet transformers

### ISSUE THREAD

**Issue by eleveyuan** [ballet/ballet#92]
* ballet version:  0.19.5
* Python version: 3.9
* Operating System: macos(intel)

### Description

the error i encountered  when i use sklearn.preprocessing.LabelBinarizer() as ballet transformer. because  the parameter of LabelBinarizer.fit()/.transformer()  is 'y'.

``` python 
import pandas as pd
from inspect import signature
from ballet import Feature
import sklearn

data = pd.DataFrame({'pet':      ['cat', 'dog', 'dog', 'fish', 'cat', 'dog', 'cat', 'fish'],
                     'children': [4., 6, 3, 3, 2, 3, 5, 4],
                     'salary':   [90., 24, 44, 27, 32, 59, 36, 27]})

input = ['pet']
transformer = sklearn.preprocessing.LabelBinarizer()
print(signature(transformer.fit))
feature = Feature(input, transformer, output='kids')


pipeline = feature.pipeline
print(pipeline.fit_transform(data))
print(pipeline.transformed_names_)
```
here is the exception info
```
(y)
Traceback (most recent call last):
  File "D:/PythonProject/import_test/test_import/test_ballet.py", line 13, in <module>
    feature = Feature(input, transformer, output='kids')
  File "D:\PythonProject\import_test\venv\lib\site-packages\ballet\feature.py", line 58, in __init__
    self.transformer = make_robust_transformer(transformer)
  File "D:\PythonProject\import_test\venv\lib\site-packages\ballet\transformer.py", line 39, in make_robust_transformer
    _validate_transformer_api(transformer)
  File "D:\PythonProject\import_test\venv\lib\site-packages\ballet\transformer.py", line 282, in _validate_transformer_api
    raise ValueError(f'Invalid signature for transformer.fit: {sig_fit}')
ValueError: Invalid signature for transformer.fit: (y)
```

### What I Did

so i naive changed ballet source code, as follow

``` python 
def _validate_transformer_api(transformer: BaseTransformer):
    if not all(
        hasattr(transformer, attr)
        for attr in ['fit', 'transform', 'fit_transform']
    ):
        raise ValueError('Transformer object missing required attribute')

    sig_fit = signature(transformer.fit)
    if '(X, y=None' not in str(sig_fit) and '(y' not in str(sig_fit): 
        raise ValueError(f'Invalid signature for transformer.fit: {sig_fit}')

    sig_transform = signature(transformer.transform)
    if '(X' not in str(sig_transform) and '(y' not in str(sig_fit):
        raise ValueError(
            f'Invalid signature for transformer.transform: {sig_transform}')
```
and i get the result what i want 
```
(y)
[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]
['kids_cat', 'kids_dog', 'kids_fish']
```

**Comment by micahjsmith** [comment]
Thanks for reporting this and including a clear example

I agree there is a need to support sklearn label transformers (like LabelBinarizer) which are reasonable to use in feature engineering with Ballet.

The naive fix will run into problems at some points and just needs to be tweaked a bit. Suppose the feature with signature `(y)` is used as part of a feature engineering pipeline along with a different feature that is supervised (like PCA). Then all the features will be passed both X and y. See https://github.com/ballet/ballet/blob/master/ballet/transformer.py#L172

So there will be a call to `LabelBinarizer(...).fit(y, y=y)` which is an error (trivial example to illustrate the Python error):
```
>>> def fit(self, y):
...     pass
... 
>>> X = 1
>>> y = 1
>>> fit(object(), X, y=y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: fit() got multiple values for argument 'y'
```

Alternative approaches
* keep the change you made to `_validate_transformer_api`, and modify transformer.py to call the underlying transformer in a different way based on its signature
* extend `Feature` constructor to wrap a label transformer with a thin wrapper that takes arguments `X, y=y` and drops `y=y`, passing `X` to the underlying label transformer

Would you like to try to make a PR with either of these approaches? I'm happy to chat further. If not, we will leave this open and work on it when we can.

PS You can see we faced this issue in another project :) https://github.com/ballet/predict-life-outcomes/commit/2c02b45dac46950238ed54626cc69efaeea68df7
